export const CATEGORIES = [
  'Mobile Phones & Tablets',
  'Computers',
  'Women clothes',
  'Men clothes',
  'Men shoes',
  'Women shoes',
  'Watches and jewelries',
  'Cars',
  'Herbals and supplements',
  'Houses',
  'Accesories and chargers',
  'Order Food',
  'Home, Furniture & Appliances',
  'Body care, soaps and perfumes',
  'Electronics',
  'vehicle parts and accesories',
  'Books',
  'Gym equipments',
  'Beauty & Personal Care',
  'Health & Medicine',
  'Vehicles',
  'Property',
  'Food stores',
  'Home, Furniture & Appliances',
  'Services',
  'Repair & Construction',
  'Commercial Equipment & Tools',
  'Babies & Kids',
  'Animals & Pets',
  'Jobs'
];

// Only these categories support Add to Cart
export const CART_CATEGORIES = new Set([
  'Herbals and supplements',
  'Food stuffs',
  'Beauty & Personal Care',
  'Health & Medicine',
  'Body care, soaps and perfumes',
  'Food, Agriculture & Farming',
]);
